# Generated by Django 2.1.7 on 2019-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedCharityContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20)),
                ('charityName', models.CharField(max_length=100)),
                ('contractAddr', models.CharField(max_length=100)),
            ],
        ),
    ]
