# Generated by Django 2.1.7 on 2020-01-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_project', '0003_deployedfundraisecontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployrequest',
            old_name='status',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='deployrequest',
            name='ipfs_hashes',
            field=models.CharField(max_length=255),
        ),
    ]
